#ifndef WEFT_DIALECT_EXECUTION_IR_SELECTEDOWNEROPINTERFACE_H
#define WEFT_DIALECT_EXECUTION_IR_SELECTEDOWNEROPINTERFACE_H

#include "mlir/IR/OpDefinition.h"

#include "Weft/Dialect/Execution/IR/SelectedOwnerOpInterface.h.inc"

#endif // WEFT_DIALECT_EXECUTION_IR_SELECTEDOWNEROPINTERFACE_H
